##### Available for Debian 9
##### Confirm remote host has sudo installed and the rsa key added.
---
- name: Prestashop 1.7.5.2 Installation
  hosts: prestashop
  tasks:

# Updating packages

  - name: Running apt-get update
    apt:
      update_cache: yes
    when: ansible_distribution == 'Debian'

# Installing third packages for Debian 9

  - name: Install base applications
    apt:
      name: "{{ packages }}"
    vars:
      packages:
      - apt-transport-https
      - lsb-release
      - ca-certificates
      - wget
      - unzip
    when: ansible_distribution == 'Debian'

  - name: Getting PHP 7.2 Repository
    apt_key:
      url: https://packages.sury.org/php/apt.gpg
      state: present
    when: ansible_distribution == 'Debian'

  - name: Adding PHP 7.2 Repository
    apt_repository:
      repo: "deb https://packages.sury.org/php/ {{ ansible_distribution_release }} main"
      state: present
    when: ansible_distribution == 'Debian'

  - name: Running apt-get update
    apt:
      update_cache: yes
    when: ansible_distribution == 'Debian'

  - name: Install third parties applications
    apt:
      name: "{{ packages }}"
    vars:
      packages:
      - php7.2
      - php7.2-cli
      - php7.2-common
      - php7.2-curl
      - php7.2-gd
      - php7.2-mysqli
      - php7.2-json
      - php7.2-fileinfo
      - php7.2-mbstring
      - php7.2-simplexml
      - php7.2-xml
      - php7.2-zip
      - libxml2-dev
      - php7.2-ldap
      - php7.2-imap
      - php7.2-xmlrpc
      - php7.2-apcu
      - php7.2-intl
      - php-cas
      - php-pear
      - openssl
      - python
      - python-mysqldb
      - apache2
      - mysql-server
    when: ansible_distribution == 'Debian'

  # enables the Apache2 module "wsgi"
  - apache2_module:
      state: present
      name: rewrite

  - name: Restart service httpd, in all cases
    service:
      name: apache2
      state: restarted
    when: ansible_distribution == 'Debian'


# Installing Prestashop

  - name: Downloading Prestashop 1.7.5.2
    get_url:
      url: https://download.prestashop.com/download/releases/prestashop_1.7.5.2.zip
      dest: /tmp/prestashop_1.7.5.2.zip
      mode: 0440
  - name: Extracting prestashop_1.7.5.2.zip into /var/www/html/
    unarchive:
      src: /tmp/prestashop_1.7.5.2.zip
      dest: /var/www/html/
      remote_src: yes
  - name: Adding permissions
    file:
      path: /var/www/html/
      owner: www-data
      group: www-data
      mode: 0750
      recurse: true
    when: ansible_distribution == 'Debian'
  - replace:
      path: /etc/apache2/apache2.conf
      regexp: '(<[dD]irectory /var/www/>[^<]*)AllowOverride None'
      replace: '\1AllowOverride All'
    when: ansible_distribution == 'Debian'

# Creatign database

  - name: Creating database and user, username glpiuser password glpiuser Now you can acces through web http://ip_address/index.php/
    mysql_db:
      name: prestashopdb
      state: present
  - mysql_user:
      name: prestashop
      password: FgHv$cv2H7g@s8Ghbnm$dcXgh3Gh
      priv: 'prestashopdb.*:ALL'
      state: present
  - name: Rebooting whole remote host
    reboot:
